version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@3.0.0
executors:
  node:
    docker:
      - image: circleci/node
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
  browsers:
    docker:
      - image: circleci/node:latest-browsers
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
jobs:
  build-compile-fend:
    executor: node
    steps:
      - checkout
      - run: cd udagram-frontend && npm install
      - run: cd udagram-frontend && npm run build

  # compile-test-fend:
  #   executor: browsers
  #   steps:
  #     - checkout
  #     - node/install-packages
  #     - run: cd udagram-frontend && npm install
  #     - run: cd udagram-frontend && npm test
  copy-frontend-files-s3:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout

      - run:
          name: Install npm
          command: |
            apk add --update npm


      - run: cd udagram-frontend && npm install
      - run: cd udagram-frontend && npm run build
      - run:
          name: Install awscli
          command: |
            pip3 install awscli 

      - run: aws s3 cp udagram-frontend/www s3://${AWS_BUCKET}/ --recursive
  deploy-backend-ebs:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - eb/setup
      - run: cd udagram-api && npm install
      - run: cd udagram-api && npm run build
      - run:
          command: |
              eb deploy Udagram-dev
              eb status
          name: Deploy Archive.zip applicaton to ebs
          working_directory: udagram-api/www/Archive.zip

workflows:
  node-build-tests:
    jobs:
      - deploy-backend-ebs
      - build-compile-fend
      # - compile-test-fend:
      #     requires:
      #       - build-compile-fend
      - copy-frontend-files-s3:
          requires:
              - build-compile-fend
            # - compile-test-fend
